name: null

channels:
  - conda-forge
  - nodefaults

dependencies:
  - gh
  - git
  - jupyter-ai
  - jupyterlab
  - jupyterlab-lsp
  - langchain-openai
  - pip
  - pip:
    - -r requirements.txt
  - python
  - python-dotenv
  - python-lsp-server
